from __future__ import annotations

import json
from pathlib import Path


OPENAPI = Path("packages/contracts/openapi.json")
OUT = Path("apps/frontend/src/api/generated.ts")


def main() -> None:
    schema = json.loads(OPENAPI.read_text(encoding="utf-8"))
    components = schema.get("components", {}).get("schemas", {})
    lines = [
        "// Generated by scripts/generate_ts_client.py from packages/contracts/openapi.json.",
        "// Do not edit manually.",
        "",
        "export type components = {",
        "  schemas: {",
    ]
    for name, definition in sorted(components.items()):
        lines.append(f"    {name}: {ts_type(definition, components)};")
    lines += [
        "  };",
        "};",
        "",
        "export type ProjectCreate = components['schemas']['ProjectCreate'];",
        "export type ProjectUpdate = components['schemas']['ProjectUpdate'];",
        "export type CurrentProcessingRunSelection = components['schemas']['CurrentProcessingRunSelection'];",
        "export type ReadinessComponent = components['schemas']['ReadinessComponent'];",
        "export type ReadinessResponse = components['schemas']['ReadinessResponse'];",
        "export type ReleaseIdentity = components['schemas']['ReleaseIdentity'];",
        "export type SourceCreate = components['schemas']['SourceCreate'];",
        "export type TimeConfigurationUpdate = components['schemas']['TimeConfigurationUpdate'];",
        "export type ReferenceFrameRequest = components['schemas']['ReferenceFrameRequest'];",
        "export type SceneGeometrySave = components['schemas']['SceneGeometrySave'];",
        "export type ReviewActionCreate = components['schemas']['ReviewActionCreate'];",
        "export type SyntheticFixtureRequest = components['schemas']['SyntheticFixtureRequest'];",
        "export type SyntheticValidationRequest = components['schemas']['SyntheticValidationRequest'];",
        "export type TaxonomyClassOut = components['schemas']['TaxonomyClassOut'];",
        "export type TaxonomyRevisionOut = components['schemas']['TaxonomyRevisionOut'];",
        "export type ClassificationPolicyOut = components['schemas']['ClassificationPolicyOut'];",
        "export type EngineeringEventOut = components['schemas']['EngineeringEventOut'];",
        "export type TrackEvidenceOut = components['schemas']['TrackEvidenceOut'];",
        "export type EngineeringLineTotalOut = components['schemas']['EngineeringLineTotalOut'];",
        "export type EngineeringLineClassTotalOut = components['schemas']['EngineeringLineClassTotalOut'];",
        "export type EngineeringDirectionClassOut = components['schemas']['EngineeringDirectionClassOut'];",
        "export type EngineeringDirectionTotalOut = components['schemas']['EngineeringDirectionTotalOut'];",
        "export type EngineeringIntervalOut = components['schemas']['EngineeringIntervalOut'];",
        "export type EngineeringIntervalRowOut = components['schemas']['EngineeringIntervalRowOut'];",
        "export type ReconciliationInvariantOut = components['schemas']['ReconciliationInvariantOut'];",
        "export type InvalidDirectionExclusionOut = components['schemas']['InvalidDirectionExclusionOut'];",
        "export type ClassificationExclusionOut = components['schemas']['ClassificationExclusionOut'];",
        "export type ReconciliationReportOut = components['schemas']['ReconciliationReportOut'];",
        "export type EngineeringDisclosuresOut = components['schemas']['EngineeringDisclosuresOut'];",
        "export type EngineeringSummaryOut = components['schemas']['EngineeringSummaryOut'];",
        "export type BenchmarkOverviewOut = components['schemas']['BenchmarkOverviewOut'];",
        "export type BenchmarkMetricsOut = components['schemas']['BenchmarkMetricsOut'];",
        "export type BenchmarkMatchPageOut = components['schemas']['BenchmarkMatchPageOut'];",
        "export type BenchmarkExperimentComparisonOut = components['schemas']['BenchmarkExperimentComparisonOut'];",
        "export type BenchmarkCorpusRevisionOut = components['schemas']['BenchmarkCorpusRevisionOut'];",
        "export type BenchmarkRunHeaderOut = components['schemas']['BenchmarkRunHeaderOut'];",
        "export type BenchmarkRunOut = components['schemas']['BenchmarkRunOut'];",
        "export type BenchmarkQualificationThreshold = components['schemas']['BenchmarkQualificationThreshold'];",
        "export type BenchmarkQualificationPolicy = components['schemas']['BenchmarkQualificationPolicy'];",
        "export type BenchmarkQualificationOut = components['schemas']['BenchmarkQualificationOut'];",
        "export type BenchmarkValidationOut = components['schemas']['BenchmarkValidationOut'];",
        "export type GroundTruthRevisionOut = components['schemas']['GroundTruthRevisionOut'];",
        "export type GuidedProcessingSettings = components['schemas']['GuidedProcessingSettings'];",
        "export type ExpertProcessingOverrides = components['schemas']['ExpertProcessingOverrides'];",
        "export type ProcessingProfileOut = components['schemas']['ProcessingProfileOut'];",
        "export type ProcessingParameterSchemaOut = components['schemas']['ProcessingParameterSchemaOut'];",
        "export type ProcessingConfigurationResolveRequest = components['schemas']['ProcessingConfigurationResolveRequest'];",
        "export type ProcessingConfigurationRevisionCreate = components['schemas']['ProcessingConfigurationRevisionCreate'];",
        "export type ProcessingConfigurationRevisionOut = components['schemas']['ProcessingConfigurationRevisionOut'];",
        "export type ConfigurationValidationOut = components['schemas']['ConfigurationValidationOut'];",
        "export type PreviewRunCreate = components['schemas']['PreviewRunCreate'];",
        "export type PreviewRunOut = components['schemas']['PreviewRunOut'];",
        "export type ConfigurationComparisonCreate = components['schemas']['ConfigurationComparisonCreate'];",
        "export type ConfigurationComparisonOut = components['schemas']['ConfigurationComparisonOut'];",
        "export type ConfigurationDiffCreate = components['schemas']['ConfigurationDiffCreate'];",
        "export type ConfigurationDiffOut = components['schemas']['ConfigurationDiffOut'];",
        "export type OperationalCandidateSelectionCreate = components['schemas']['OperationalCandidateSelectionCreate'];",
        "export type OperationalCandidateSelectionOut = components['schemas']['OperationalCandidateSelectionOut'];",
        "export type CapabilityValidationCreate = components['schemas']['CapabilityValidationCreate'];",
        "export type CapabilityValidationOut = components['schemas']['CapabilityValidationOut'];",
        "",
    ]
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {OUT}")


def ts_type(definition: dict, components: dict) -> str:
    if "$ref" in definition:
        return ref_name(definition["$ref"])
    if "anyOf" in definition:
        return " | ".join(ts_type(item, components) for item in definition["anyOf"])
    if "const" in definition:
        return json.dumps(definition["const"])
    if "enum" in definition:
        return " | ".join(json.dumps(value) for value in definition["enum"])
    kind = definition.get("type")
    if kind == "object" or "properties" in definition:
        required = set(definition.get("required", []))
        props = []
        for key, value in definition.get("properties", {}).items():
            optional = "" if key in required else "?"
            props.append(f"{json.dumps(key)}{optional}: {ts_type(value, components)}")
        if definition.get("additionalProperties") is True:
            props.append("[key: string]: unknown")
        elif isinstance(definition.get("additionalProperties"), dict):
            props.append(f"[key: string]: {ts_type(definition['additionalProperties'], components)}")
        if not props:
            return "Record<string, never>"
        return "{ " + "; ".join(props) + " }"
    if kind == "array":
        return f"{ts_type(definition.get('items', {}), components)}[]"
    if kind in {"integer", "number"}:
        return "number"
    if kind == "boolean":
        return "boolean"
    if kind == "null":
        return "null"
    if kind == "string":
        return "string"
    return "unknown"


def ref_name(ref: str) -> str:
    return "components['schemas']['" + ref.rsplit("/", 1)[-1] + "']"


if __name__ == "__main__":
    main()
