export type Language = "th" | "en";

export const approvedThaiEnglishTerms = [
  "Traffic Video Analytics",
  "TVA",
  "PTS",
  "PHF",
  "FFmpeg",
  "ROI",
  "CSV",
  "SQLite",
  "API",
  "AI",
  "Trial",
  "trial",
  "review",
  "results",
  "Milestone",
  "milestone",
  "preview",
  "reference image",
  "Reference image",
  "frame",
  "movement",
  "manifest",
  "scene revision",
  "pilot",
  "QC",
  "A to B",
  "B to A",
  "Bidirectional"
] as const;

const en = {
  product: "Traffic Video Analytics",
  project: "Rama IX traffic study",
  stateCurrent: "Current result",
  stateStale: "Stale result",
  save: "Saved",
  saving: "Saving",
  retry: "Retry",
  backendUnavailable: "Backend unavailable",
  noProject: "No project selected",
  command: "Command",
  primary: "Continue",
  create: "Create project",
  source: "Source and time",
  scene: "Scene and count lines",
  process: "Mock processing",
  aiTrial: "Start processing job",
  aiTrialUnavailableBody: "Choose synthetic validation or the local real-video pilot. Both outputs remain provisional and require human review.",
  processingMode: "Processing mode",
  syntheticMode: "Synthetic validation",
  realVideoMode: "Real video inference",
  syntheticReady: "Deterministic fixture; no model runtime required.",
  realVideoReady: "Runtime, weights, FFmpeg, and ByteTrack are ready.",
  realVideoBlocked: "Real-video inference is unavailable until the local runtime and media tools are ready.",
  realVideoConfigRequired: "Save a processing configuration revision in Operational settings before starting a real-video full run.",
  realVideoDisclaimer: "Technical trial only. YOLO11n + ByteTrack outputs remain provisional and require human review; no formal accuracy claim is made.",
  syntheticProcessingDisclaimer: "Synthetic validation output is for workflow testing only and is not a certified count.",
  processingJob: "Processing job",
  processingQueued: "Queued",
  processingRunning: "Running",
  processingComplete: "Complete",
  processingFailed: "Failed",
  processingCancelled: "Cancelled",
  processingPartialBlocked: "Partial, failed, cancelled, or stale outputs cannot be certified or exported.",
  cancelProcessing: "Cancel job",
  rerunProcessing: "Run again",
  noProcessingJob: "No processing job has been submitted for this scene.",
  review: "Review events",
  results: "Results",
  certify: "Certification",
  export: "Export",
  projectName: "Project name",
  location: "Location",
  saveProject: "Save project",
  selectVideo: "Select local video",
  mockSource: "Use mock source",
  startTime: "Recording start",
  timezone: "Timezone",
  analysisStart: "Analysis start PTS ms",
  analysisEnd: "Analysis end PTS ms",
  confirmTime: "Confirm time window",
  sourceAction: "Confirm source and time",
  sceneAction: "Save scene",
  processAction: "Start mock processing",
  approve: "Approve",
  correct: "Change",
  certifyAction: "Certify this result version",
  exportAction: "Create CSV manifest",
  workspaceTitle: "Source and time setup",
  reviewTitle: "Required review queue",
  resultTitle: "One-hour result table",
  gallery: "Component state preview",
  empty: "No items are available in this step",
  emptyBody: "Create a project to start the persisted workflow.",
  warning: "Mandatory QC must be resolved before certification",
  error: "Stale results cannot be exported",
  errorTitle: "Controlled error state",
  loading: "Loading",
  loadingBody: "Loading persisted state from SQLite through the backend API.",
  startupEyebrow: "Local startup",
  startupTitle: "Opening the application shell",
  startupFailedTitle: "Startup needs attention",
  startupChecking: "Checking",
  startupWaiting: "Waiting",
  startupReady: "Ready",
  startupDegraded: "Degraded",
  startupFailed: "Failed",
  startupFrontend: "Frontend shell",
  startupFrontendReady: "The browser UI is available.",
  startupBackend: "Backend API",
  startupBackendWaiting: "Waiting for the local backend to respond.",
  startupStorage: "Project storage",
  startupStorageWaiting: "Waiting to confirm SQLite project storage.",
  startupVideoRuntime: "Video runtime",
  startupVideoRuntimeWaiting: "Checking FFmpeg and ffprobe without blocking project setup.",
  startupAiRuntime: "AI runtime",
  startupAiRuntimeWaiting: "Checking the detector, tracker, model weights, and device capability.",
  startupWorker: "Processing worker",
  startupWorkerWaiting: "Waiting for a fresh backend-observable worker heartbeat.",
  startupWorkerHeartbeatWaiting: "Waiting for a fresh backend-observable worker heartbeat.",
  startupProcessing: "Processing capability",
  startupProcessingWaiting: "Real-media processing is blocked until the required worker and runtime are ready.",
  staleBody: "Calculation-dependent records are stale until the workflow is rerun.",
  certified: "Certified by reviewer",
  interval: "15-minute interval",
  phf: "PHF",
  unresolved: "Unresolved",
  noEvents: "No run events yet",
  state: "State",
  count: "Count",
  evidenceUnavailable: "No source selected",
  sceneEditorTitle: "Scene geometry setup",
  sceneCoordinateContract: "Normalized x,y 0-1 from the reference frame top-left",
  referenceReady: "Reference ready",
  referenceMissing: "Reference image missing",
  mediaRuntimeUnavailable: "FFmpeg unavailable",
  mediaRuntimeBody: "Install ffmpeg and ffprobe or configure PATH before extracting reference frames.",
  sceneTools: "Scene tools",
  extractReference: "Extract reference",
  addLine: "Add line",
  addRoi: "Add ROI",
  deleteSelected: "Delete selected",
  referenceFrameAlt: "Reference image for scene setup",
  videoPreview: "Source video preview",
  sceneOverlay: "Scene geometry overlay",
  lineName: "Counting line name",
  directionMode: "Active directions",
  sideAName: "Side A name",
  sideBName: "Side B name",
  sideALabelDefault: "Side A",
  sideBLabelDefault: "Side B",
  approachName: "Approach name",
  movementName: "Movement",
  analystNote: "Analyst note",
  defaultLineName: "Counting line",
  defaultRoiName: "Analysis area",
  synthetic: "Local-only setup",
  syntheticDisclaimer: "Synthetic validation uses deterministic fixture tracks. It is a workflow check, not a certified count.",
  validateSynthetic: "Validate synthetic tracks",
  runSynthetic: "Run synthetic counting",
  syntheticFixture: "Synthetic fixture",
  eventLedger: "Event ledger",
  rawTotals: "Raw totals",
  reviewedTotals: "Reviewed totals",
  excludedTotals: "Excluded totals",
  direction: "Direction",
  line: "Counting line",
  trackId: "Track ID",
  classLabel: "Synthetic class",
  provisionalClass: "Provisional observable class",
  reportingBin: "Reporting bin",
  reviewStatus: "Review status",
  reverseReview: "Reverse review",
  exportSynthetic: "Create synthetic export manifest",
  validationOnly: "Validation-only output",
  openProject: "Open project",
  onboardingEyebrow: "Start here",
  onboardingTitle: "Create or open a project before loading video",
  onboardingFlow: "Setup workflow",
  createProjectFirst: "Create a project first",
  createProjectFirstBody: "A project stores the video, time window, reference image, detection area, counting lines, and scene revisions.",
  openProjectBody: "Open a saved project to continue setup.",
  noExistingProjects: "No saved projects are available yet.",
  uploadingVideo: "Uploading and validating video",
  validatingTime: "Validating time window",
  preparingReferenceImage: "Preparing reference image",
  referencePreparingAfterUpload: "The app will extract a midpoint reference image after the video probe succeeds.",
  referencePreparingForWindow: "The app will refresh the reference image at the midpoint of the selected analysis window.",
  referencePreparingManual: "Refreshing the reference image from the current analysis window.",
  refreshReferenceImage: "Refresh reference image",
  referenceImage: "Reference image",
  createDetectionArea: "Create detection area",
  replaceDetectionArea: "Replace detection area",
  detectionArea: "Detection area",
  deleteDetectionArea: "Delete detection area",
  areaName: "Area name",
  oneRoiPilot: "Pilot setup uses one active detection area. Replace it when the camera view changes.",
  countingLine: "Counting line",
  countingMode: "Counting mode",
  countOneDirection: "Count Side A to Side B only",
  countReverseDirection: "Count Side B to Side A only",
  countBothDirections: "Count both side transitions",
  swapDirections: "Swap side names",
  deleteCountingLine: "Delete counting line",
  geometryObjects: "Scene objects",
  noGeometrySelected: "Select the detection area or a counting line to edit it.",
  undo: "Undo",
  redo: "Redo",
  sceneSaved: "Scene saved",
  sceneNeedsSetup: "Scene needs setup",
  unsavedChanges: "Unsaved changes",
  abandonSceneChanges: "Discard unsaved scene changes and open another project?",
  inspectorTitle: "Inspector",
  engineeringTitle: "Engineering count output",
  provisionalAutomaticClassification: "Provisional automatic classification",
  taxonomyRevision: "Taxonomy revision",
  mappingRevision: "Mapping revision",
  policyRevision: "Classification policy revision",
  engineeringReady: "Structurally ready",
  structurallyValid: "Structurally valid",
  structurallyInvalid: "Structurally invalid",
  lineTotals: "Line totals",
  directionMatrix: "Class × direction matrix",
  intervalTable: "15-minute interval table",
  unknownClass: "Unknown",
  ambiguousClass: "Ambiguous",
  sourceRelativeTime: "Source-relative time",
  recordingLocalTime: "Recording local time",
  eventTotalDisclosure: "Across multiple lines this is an event total, not a unique-vehicle total.",
  unsupportedClassDisclosure: "COCO detector labels do not establish the TIMS 13-class taxonomy.",
  noEngineeringResult: "No engineering result is available for this run.",
  noIntervalEvents: "No events for the selected line in the configured interval window.",
  engineeringStale: "Engineering output is stale and must be regenerated.",
  invalidDirectionWarning: "Invalid source directions are excluded from engineering dimensions",
  classificationConsistencyWarning: "Classification status/class inconsistencies are excluded from engineering dimensions",
  classTotal: "Class total",
  canonicalDirection: "Canonical direction",
  timeStatus: "Time status",
  intervalPartial: "Partial interval",
  intervalNonZeroDisclosure: "Interval rows with zero events are omitted; the class matrix keeps zero totals visible.",
  benchmarkWorkspace: "Benchmark workspace",
  benchmarkBack: "Back to project",
  benchmarkEyebrow: "Milestone 6C / evidence ledger",
  benchmarkTitle: "Accuracy and calibration workspace",
  benchmarkBody: "Compare reviewed ground truth with immutable automatic results using source-relative PTS.",
  benchmarkReload: "Refresh benchmark",
  benchmarkEmptyTitle: "No benchmark corpus is loaded",
  benchmarkEmptyBody: "Validate and import a rights-aware corpus manifest from the local benchmark CLI before evaluating a run.",
  benchmarkCorpus: "Corpus revision",
  benchmarkSources: "Sources",
  benchmarkRights: "Rights coverage",
  benchmarkSplits: "Splits",
  benchmarkLatestRun: "Latest evaluation",
  benchmarkNoRun: "No evaluation run yet",
  benchmarkMetricsPending: "Loading metric snapshots",
  benchmarkMetricEvent: "Event metrics",
  benchmarkMetricCount: "Count error",
  benchmarkMetricDirection: "Direction",
  benchmarkMetricClass: "Engineering class",
  benchmarkMetricTimestamp: "Timestamp",
  benchmarkMetricFragmentation: "Track fragmentation",
  benchmarkMetricThroughput: "Throughput provenance",
  benchmarkQualification: "Qualification gates",
  benchmarkQualificationBody: "A candidate is not a production or pilot approval.",
  benchmarkLimitations: "Limitations",
  benchmarkRightsStatus: "rights status",
  benchmarkCalibration: "calibration",
  benchmarkHoldout: "holdout",
  benchmarkRunStatus: "run status",
  benchmarkAutomaticResult: "automatic result",
  benchmarkQualificationStatus: "qualification",
  benchmarkSourcePts: "source PTS",
  benchmarkPrecision: "precision",
  benchmarkRecall: "recall",
  benchmarkF1: "F1",
  benchmarkFalsePositive: "false positives",
  benchmarkFalseNegative: "false negatives",
  benchmarkDuplicates: "duplicates",
  benchmarkMisses: "misses",
  benchmarkDirectionAccuracy: "direction accuracy",
  benchmarkUnknownRate: "unknown / ambiguous rate",
  benchmarkTimestampMae: "timestamp MAE",
  benchmarkTimestampP95: "timestamp p95",
  benchmarkFragmentationAvailability: "availability",
  benchmarkProcessingRatio: "processing / video ratio",
  benchmarkRealTime: "real-time claim",
  benchmarkGroundTruth: "ground truth",
  benchmarkDiagnostics: "Match diagnostics",
  benchmarkDiagnosticsBody: "Review false, missed, duplicate, direction and class errors without changing automatic events.",
  benchmarkDiagnosticCategory: "category",
  benchmarkDiagnosticAutomaticId: "automatic event",
  benchmarkDiagnosticGroundTruthId: "ground-truth event",
  benchmarkDiagnosticTimestampError: "timestamp error",
  benchmarkDiagnosticFlags: "secondary flags",
  benchmarkDiagnosticNoRows: "No diagnostic rows for this run.",
  benchmarkExperiment: "Experiment comparison",
  benchmarkExperimentStatus: "comparison status",
  benchmarkExperimentCandidates: "candidate configurations",
  benchmarkExperimentRuns: "evaluated runs",
  benchmarkExperimentPareto: "Pareto status",
  benchmarkExperimentNoRun: "No persisted experiment suite is available.",
  benchmarkNoPolicy: "No owner-approved threshold policy is configured.",
  benchmarkIncomplete: "This benchmark run is incomplete and was not scored because the selected automatic result is not scorable.",
  benchmarkBlockers: "Scoring blockers",
  benchmarkThresholds: "Threshold evaluation",
  benchmarkThresholdPolicy: "Policy revision",
  benchmarkThresholdMetric: "Metric path",
  benchmarkThresholdObserved: "Observed",
  benchmarkThresholdRequired: "Required",
  benchmarkThresholdAvailability: "Availability",
  benchmarkThresholdResult: "Result",
  benchmarkThresholdReason: "Reason",
  benchmarkThresholdPass: "PASS",
  benchmarkThresholdFail: "HOLD",
  pilotRelease: "Pilot Release",
  versionLabel: "Version",
  currentRun: "Current processing run",
  selectRun: "Select run",
  selectedRun: "Selected",
  runHistory: "Run history",
  runSelectionHelp: "Select a completed run explicitly. Historical runs remain available and are not replaced automatically.",
  runNotReady: "Only completed runs with a result can become current.",
  coreReady: "Core app ready",
  processingBlocked: "Real processing blocked",
  readinessComponents: "Readiness components"
} as const;

type CopyCatalog = { [Key in keyof typeof en]: string };

const th: CopyCatalog = {
  startupAiRuntime: "ระบบ AI",
  startupAiRuntimeWaiting: "กำลังตรวจ detector, tracker, model weights และความสามารถของอุปกรณ์",
  startupProcessing: "ความสามารถด้านการประมวลผล",
  startupProcessingWaiting: "การประมวลผลจากสื่อจริงยังถูกบล็อกจนกว่า worker และ runtime ที่ต้องใช้จะพร้อม",
  startupWorkerHeartbeatWaiting: "กำลังรอ heartbeat ของ worker ที่ backend ตรวจสอบได้",
  product: "Traffic Video Analytics",
  project: "โครงการสำรวจจราจรพระราม 9",
  stateCurrent: "ผลปัจจุบัน",
  stateStale: "ผลล้าสมัย",
  save: "บันทึกแล้ว",
  saving: "กำลังบันทึก",
  retry: "ลองอีกครั้ง",
  backendUnavailable: "เชื่อมต่อระบบหลังบ้านไม่ได้",
  noProject: "ยังไม่ได้เลือกโครงการ",
  command: "คำสั่ง",
  primary: "ดำเนินการต่อ",
  create: "สร้างโครงการ",
  source: "แหล่งวิดีโอและเวลา",
  scene: "ฉากและเส้นนับ",
  process: "การประมวลผลทดสอบ",
  aiTrial: "เริ่มงานประมวลผล",
  aiTrialUnavailableBody: "เลือกการตรวจสอบสังเคราะห์หรือ technical trial จากวิดีโอจริง ผลทั้งสองแบบยังเป็น provisional และต้องมี human review",
  processingMode: "โหมดการประมวลผล",
  syntheticMode: "ตรวจสอบด้วยข้อมูลสังเคราะห์",
  realVideoMode: "อนุมานจากวิดีโอจริง",
  syntheticReady: "ใช้ fixture ที่ทำซ้ำได้ และไม่ต้องใช้ model runtime",
  realVideoReady: "runtime, weights, FFmpeg และ ByteTrack พร้อมใช้งาน",
  realVideoBlocked: "ยังใช้วิดีโอจริงไม่ได้จนกว่า runtime และเครื่องมือสื่อจะพร้อม",
  realVideoConfigRequired: "บันทึก configuration revision ในการตั้งค่าการประมวลผลก่อนเริ่มงานวิดีโอจริงแบบเต็มช่วง",
  realVideoDisclaimer: "เป็น technical trial เท่านั้น ผลจาก YOLO11n + ByteTrack เป็น provisional และต้องมี human review; ไม่ใช่การอ้างความแม่นยำอย่างเป็นทางการ",
  syntheticProcessingDisclaimer: "ผลตรวจสอบสังเคราะห์ใช้ทดสอบ workflow เท่านั้น ไม่ใช่ผลนับที่รับรองแล้ว",
  processingJob: "งานประมวลผล",
  processingQueued: "รอคิว",
  processingRunning: "กำลังทำงาน",
  processingComplete: "เสร็จแล้ว",
  processingFailed: "ไม่สำเร็จ",
  processingCancelled: "ยกเลิกแล้ว",
  processingPartialBlocked: "ผลที่ยังไม่ครบ ล้มเหลว ถูกยกเลิก หรือล้าสมัย จะรับรองหรือส่งออกไม่ได้",
  cancelProcessing: "ยกเลิกงาน",
  rerunProcessing: "รันใหม่",
  noProcessingJob: "ยังไม่มีงานประมวลผลสำหรับ scene นี้",
  review: "ตรวจสอบเหตุการณ์",
  results: "ผลลัพธ์",
  certify: "การรับรองผล",
  export: "ส่งออก",
  projectName: "ชื่อโครงการ",
  location: "สถานที่",
  saveProject: "บันทึกโครงการ",
  selectVideo: "เลือกวิดีโอในเครื่อง",
  mockSource: "ใช้แหล่งวิดีโอจำลอง",
  startTime: "เวลาเริ่มบันทึกจริง",
  timezone: "เขตเวลา",
  analysisStart: "เวลาเริ่มวิเคราะห์ PTS ms",
  analysisEnd: "เวลาสิ้นสุดวิเคราะห์ PTS ms",
  confirmTime: "ยืนยันช่วงเวลา",
  sourceAction: "ยืนยันแหล่งวิดีโอและเวลา",
  sceneAction: "บันทึกฉาก",
  processAction: "เริ่มประมวลผลทดสอบ",
  approve: "อนุมัติ",
  correct: "แก้ไข",
  certifyAction: "รับรองผลเวอร์ชันนี้",
  exportAction: "สร้าง manifest CSV",
  workspaceTitle: "ตั้งค่าแหล่งวิดีโอและเวลา",
  reviewTitle: "คิวรายการที่ต้องตรวจสอบ",
  resultTitle: "ตารางผลหนึ่งชั่วโมง",
  gallery: "ตัวอย่างสถานะคอมโพเนนต์",
  empty: "ยังไม่มีรายการในขั้นตอนนี้",
  emptyBody: "สร้างโครงการเพื่อเริ่มเวิร์กโฟลว์ที่บันทึกลงฐานข้อมูล",
  warning: "ต้องจัดการ QC บังคับให้ครบก่อนรับรองผล",
  error: "ส่งออกผลล้าสมัยเป็นผลปัจจุบันไม่ได้",
  errorTitle: "สถานะข้อผิดพลาดที่ควบคุมได้",
  loading: "กำลังโหลด",
  loadingBody: "กำลังโหลดสถานะที่บันทึกไว้จาก SQLite ผ่าน API หลังบ้าน",
  startupEyebrow: "การเปิดใช้งานในเครื่อง",
  startupTitle: "กำลังเปิดหน้าจอหลัก",
  startupFailedTitle: "ต้องตรวจสอบการเปิดใช้งาน",
  startupChecking: "กำลังตรวจ",
  startupWaiting: "รอ",
  startupReady: "พร้อม",
  startupDegraded: "ใช้ได้บางส่วน",
  startupFailed: "ไม่สำเร็จ",
  startupFrontend: "หน้าจอ Frontend",
  startupFrontendReady: "หน้าจอในเบราว์เซอร์ใช้งานได้",
  startupBackend: "API หลังบ้าน",
  startupBackendWaiting: "กำลังรอ API ในเครื่องตอบกลับ",
  startupStorage: "พื้นที่เก็บโครงการ",
  startupStorageWaiting: "กำลังตรวจ SQLite สำหรับโครงการ",
  startupVideoRuntime: "ระบบวิดีโอ",
  startupVideoRuntimeWaiting: "กำลังตรวจ FFmpeg และ ffprobe โดยไม่บล็อกการตั้งค่าโครงการ",
  startupWorker: "เวิร์กเกอร์ประมวลผล",
  startupWorkerWaiting: "การประมวลผลพร้อมหลังหน้าจอหลักเปิดได้",
  staleBody: "ข้อมูลที่มีผลต่อการคำนวณล้าสมัยจนกว่าจะประมวลผลใหม่",
  certified: "รับรองโดยผู้ตรวจสอบแล้ว",
  interval: "ช่วง 15 นาที",
  phf: "PHF",
  unresolved: "ยังไม่เสร็จ",
  noEvents: "ยังไม่มีเหตุการณ์จากรัน",
  state: "สถานะ",
  count: "จำนวน",
  evidenceUnavailable: "ยังไม่ได้เลือกแหล่งวิดีโอ",
  sceneEditorTitle: "ตั้งค่าฉากและเรขาคณิต",
  sceneCoordinateContract: "พิกัด x,y แบบ normalized 0-1 จากมุมซ้ายบนของ reference frame",
  referenceReady: "มี reference frame แล้ว",
  referenceMissing: "ยังไม่มี reference frame",
  mediaRuntimeUnavailable: "ยังใช้ FFmpeg ไม่ได้",
  mediaRuntimeBody: "ติดตั้ง ffmpeg และ ffprobe หรือกำหนด PATH ก่อนดึง reference frame",
  sceneTools: "เครื่องมือฉาก",
  extractReference: "ดึง reference frame",
  addLine: "เพิ่มเส้นนับ",
  addRoi: "เพิ่ม ROI",
  deleteSelected: "ลบรายการที่เลือก",
  referenceFrameAlt: "Reference frame สำหรับตั้งค่าฉาก",
  videoPreview: "ตัวอย่างวิดีโอต้นฉบับ",
  sceneOverlay: "โอเวอร์เลย์เรขาคณิตของฉาก",
  lineName: "ชื่อเส้นนับ",
  directionMode: "ทิศทางที่นับ",
  sideAName: "ชื่อฝั่ง A",
  sideBName: "ชื่อฝั่ง B",
  sideALabelDefault: "ฝั่ง A",
  sideBLabelDefault: "ฝั่ง B",
  approachName: "ชื่อทางเข้า",
  movementName: "movement",
  analystNote: "หมายเหตุผู้วิเคราะห์",
  defaultLineName: "เส้นนับ",
  defaultRoiName: "พื้นที่วิเคราะห์",
  synthetic: "ตั้งค่าในเครื่องเท่านั้น",
  syntheticDisclaimer: "โหมดสังเคราะห์ใช้ track fixture ที่ทำซ้ำได้ เป็นการตรวจสอบ workflow ไม่ใช่ผลนับที่รับรองแล้ว",
  validateSynthetic: "ตรวจสอบแทร็กสังเคราะห์",
  runSynthetic: "รันการนับสังเคราะห์",
  syntheticFixture: "ชุดทดสอบสังเคราะห์",
  eventLedger: "บัญชีเหตุการณ์",
  rawTotals: "ยอดดิบ",
  reviewedTotals: "ยอดหลังตรวจสอบ",
  excludedTotals: "ยอดที่ไม่นับ",
  direction: "ทิศทาง",
  line: "เส้นนับ",
  trackId: "รหัสแทร็ก",
  classLabel: "ประเภทสังเคราะห์",
  provisionalClass: "ประเภทวัตถุเบื้องต้น",
  reportingBin: "ช่วงรายงาน",
  reviewStatus: "สถานะการตรวจสอบ",
  reverseReview: "ย้อนกลับการตรวจสอบ",
  exportSynthetic: "สร้าง manifest ส่งออกผลสังเคราะห์",
  validationOnly: "ผลสำหรับตรวจสอบเท่านั้น",
  openProject: "เปิดโครงการ",
  onboardingEyebrow: "เริ่มจากตรงนี้",
  onboardingTitle: "สร้างหรือเปิดโครงการก่อนโหลดวิดีโอ",
  onboardingFlow: "ลำดับการตั้งค่า",
  createProjectFirst: "สร้างโครงการก่อน",
  createProjectFirstBody: "โครงการเก็บวิดีโอ ช่วงเวลา reference image พื้นที่ตรวจจับ เส้นนับ และประวัติ scene revision",
  openProjectBody: "เปิดโครงการที่บันทึกไว้เพื่อทำงานต่อ",
  noExistingProjects: "ยังไม่มีโครงการที่บันทึกไว้",
  uploadingVideo: "กำลังอัปโหลดและตรวจวิดีโอ",
  validatingTime: "กำลังตรวจช่วงเวลา",
  preparingReferenceImage: "กำลังเตรียม reference image",
  referencePreparingAfterUpload: "ระบบจะดึง reference image ที่กึ่งกลางวิดีโอหลังตรวจไฟล์ผ่าน",
  referencePreparingForWindow: "ระบบจะปรับ reference image ไปที่กึ่งกลางช่วงวิเคราะห์ที่เลือก",
  referencePreparingManual: "กำลังดึง reference image ใหม่จากช่วงวิเคราะห์ปัจจุบัน",
  refreshReferenceImage: "ปรับ reference image ใหม่",
  referenceImage: "ภาพอ้างอิง",
  createDetectionArea: "สร้างพื้นที่ตรวจจับ",
  replaceDetectionArea: "แทนที่พื้นที่ตรวจจับ",
  detectionArea: "พื้นที่ตรวจจับ",
  deleteDetectionArea: "ลบพื้นที่ตรวจจับ",
  areaName: "ชื่อพื้นที่",
  oneRoiPilot: "รุ่น pilot ใช้พื้นที่ตรวจจับที่เปิดใช้งานหนึ่งพื้นที่ ให้แทนที่พื้นที่เดิมเมื่อมุมกล้องเปลี่ยน",
  countingLine: "เส้นนับ",
  countingMode: "รูปแบบการนับ",
  countOneDirection: "นับจากฝั่ง A ไปฝั่ง B เท่านั้น",
  countReverseDirection: "นับจากฝั่ง B ไปฝั่ง A เท่านั้น",
  countBothDirections: "นับการข้ามทั้งสองทิศทาง",
  swapDirections: "สลับชื่อฝั่ง",
  deleteCountingLine: "ลบเส้นนับ",
  geometryObjects: "วัตถุในฉาก",
  noGeometrySelected: "เลือกพื้นที่ตรวจจับหรือเส้นนับเพื่อแก้ไข",
  undo: "ย้อนกลับ",
  redo: "ทำซ้ำ",
  sceneSaved: "บันทึกฉากแล้ว",
  sceneNeedsSetup: "ต้องตั้งค่าฉาก",
  unsavedChanges: "ยังไม่ได้บันทึก",
  abandonSceneChanges: "ละทิ้งการแก้ไขฉากที่ยังไม่ได้บันทึกแล้วเปิดโครงการอื่นหรือไม่",
  inspectorTitle: "ตัวตรวจสอบ",
  engineeringTitle: "ผลนับเชิงวิศวกรรม",
  provisionalAutomaticClassification: "การจำแนกอัตโนมัติเป็นการจัดประเภทเบื้องต้น",
  taxonomyRevision: "รุ่นอนุกรมวิธาน",
  mappingRevision: "รุ่นตารางจับคู่",
  policyRevision: "รุ่นนโยบายจำแนกประเภท",
  engineeringReady: "พร้อมเชิงโครงสร้าง",
  structurallyValid: "โครงสร้างถูกต้อง",
  structurallyInvalid: "โครงสร้างไม่ถูกต้อง",
  lineTotals: "ยอดรวมตามเส้นนับ",
  directionMatrix: "ตารางคลาสตามทิศทาง",
  intervalTable: "ตารางช่วงเวลา 15 นาที",
  unknownClass: "ไม่ทราบประเภท",
  ambiguousClass: "ไม่ชัดเจน",
  sourceRelativeTime: "เวลาสัมพัทธ์ของแหล่งวิดีโอ",
  recordingLocalTime: "เวลาท้องถิ่นของการบันทึก",
  eventTotalDisclosure: "ยอดรวมหลายเส้นเป็นจำนวนเหตุการณ์ ไม่ใช่จำนวนยานพาหนะที่ไม่ซ้ำกัน",
  unsupportedClassDisclosure: "ชื่อคลาส COCO ไม่ได้ยืนยันความสามารถในการจำแนก TIMS 13 คลาส",
  noEngineeringResult: "ยังไม่มีผลนับเชิงวิศวกรรมสำหรับงานนี้",
  noIntervalEvents: "ไม่พบเหตุการณ์ของเส้นที่เลือกในช่วงเวลาที่กำหนด",
  engineeringStale: "ผลนับเชิงวิศวกรรมล้าสมัย ต้องประมวลผลใหม่",
  invalidDirectionWarning: "ตัดเหตุการณ์ที่มีทิศทางต้นทางไม่ถูกต้องออกจากมิติเชิงวิศวกรรม",
  classificationConsistencyWarning: "ตัดเหตุการณ์ที่สถานะและคลาสการจำแนกไม่สอดคล้องกันออกจากมิติเชิงวิศวกรรม",
  classTotal: "ยอดรวมตามคลาส",
  canonicalDirection: "ทิศทางมาตรฐาน",
  timeStatus: "สถานะเวลา",
  intervalPartial: "ช่วงเวลาไม่เต็มช่วง",
  intervalNonZeroDisclosure: "ซ่อนแถวช่วงเวลาที่ไม่มีเหตุการณ์ แต่ตารางคลาสยังแสดงยอดศูนย์",
  benchmarkWorkspace: "พื้นที่ทดสอบมาตรฐาน",
  benchmarkBack: "กลับไปยังโครงการ",
  benchmarkEyebrow: "Milestone 6C / บัญชีหลักฐาน",
  benchmarkTitle: "พื้นที่ประเมินความแม่นยำและปรับเทียบ",
  benchmarkBody: "เปรียบเทียบ ground truth ที่ผ่านการตรวจทานกับผลอัตโนมัติแบบแก้ไขไม่ได้ โดยใช้ PTS สัมพัทธ์กับวิดีโอ",
  benchmarkReload: "รีเฟรชข้อมูลทดสอบ",
  benchmarkEmptyTitle: "ยังไม่มีคลังทดสอบ",
  benchmarkEmptyBody: "ตรวจสอบและนำเข้า manifest ที่ระบุสิทธิ์จาก CLI ในเครื่องก่อนประเมินผล",
  benchmarkCorpus: "รุ่นคลังทดสอบ",
  benchmarkSources: "แหล่งวิดีโอ",
  benchmarkRights: "ความครอบคลุมสิทธิ์",
  benchmarkSplits: "ชุดข้อมูล",
  benchmarkLatestRun: "ผลประเมินล่าสุด",
  benchmarkNoRun: "ยังไม่มีรอบประเมิน",
  benchmarkMetricsPending: "กำลังโหลดสแนปชอตเมตริก",
  benchmarkMetricEvent: "เมตริกเหตุการณ์",
  benchmarkMetricCount: "ความคลาดเคลื่อนจำนวน",
  benchmarkMetricDirection: "ทิศทาง",
  benchmarkMetricClass: "ประเภทยานพาหนะเชิงวิศวกรรม",
  benchmarkMetricTimestamp: "เวลาเหตุการณ์",
  benchmarkMetricFragmentation: "การแตกตัวของแทร็ก",
  benchmarkMetricThroughput: "หลักฐานประสิทธิภาพ",
  benchmarkQualification: "ประตูการรับรอง",
  benchmarkQualificationBody: "สถานะ candidate ไม่ใช่การอนุมัติสำหรับ production หรือ pilot",
  benchmarkLimitations: "ข้อจำกัด",
  benchmarkRightsStatus: "สถานะสิทธิ์",
  benchmarkCalibration: "ปรับเทียบ",
  benchmarkHoldout: "ทดสอบคงไว้",
  benchmarkRunStatus: "สถานะรอบประเมิน",
  benchmarkAutomaticResult: "ผลอัตโนมัติ",
  benchmarkQualificationStatus: "สถานะรับรอง",
  benchmarkSourcePts: "PTS ของแหล่งข้อมูล",
  benchmarkPrecision: "ความเที่ยงตรง (precision)",
  benchmarkRecall: "การครอบคลุม (recall)",
  benchmarkF1: "ค่า F1",
  benchmarkFalsePositive: "ผลบวกลวง",
  benchmarkFalseNegative: "ผลลบลวง",
  benchmarkDuplicates: "เหตุการณ์ซ้ำ",
  benchmarkMisses: "เหตุการณ์ที่พลาด",
  benchmarkDirectionAccuracy: "ความถูกต้องของทิศทาง",
  benchmarkUnknownRate: "อัตราไม่ทราบ / ไม่ชัดเจน",
  benchmarkTimestampMae: "MAE ของเวลา",
  benchmarkTimestampP95: "p95 ของเวลา",
  benchmarkFragmentationAvailability: "ความพร้อมของข้อมูล",
  benchmarkProcessingRatio: "อัตราเวลาประมวลผล / วิดีโอ",
  benchmarkRealTime: "สถานะ real-time",
  benchmarkGroundTruth: "ข้อมูลอ้างอิง ground truth",
  benchmarkDiagnostics: "รายละเอียดการจับคู่",
  benchmarkDiagnosticsBody: "ตรวจสอบเหตุการณ์เกิน ขาด ซ้ำ ทิศทางผิด และคลาสผิด โดยไม่แก้ไขเหตุการณ์อัตโนมัติ",
  benchmarkDiagnosticCategory: "หมวดหมู่",
  benchmarkDiagnosticAutomaticId: "เหตุการณ์อัตโนมัติ",
  benchmarkDiagnosticGroundTruthId: "เหตุการณ์ ground truth",
  benchmarkDiagnosticTimestampError: "ค่าคลาดเคลื่อนเวลา",
  benchmarkDiagnosticFlags: "ธงความผิดพลาดเพิ่มเติม",
  benchmarkDiagnosticNoRows: "ไม่พบรายการวินิจฉัยสำหรับรอบนี้",
  benchmarkExperiment: "การเปรียบเทียบการทดลอง",
  benchmarkExperimentStatus: "สถานะการเปรียบเทียบ",
  benchmarkExperimentCandidates: "รุ่นการตั้งค่าที่ทดสอบ",
  benchmarkExperimentRuns: "รอบที่ประเมิน",
  benchmarkExperimentPareto: "สถานะ Pareto",
  benchmarkExperimentNoRun: "ยังไม่มีชุดการทดลองที่บันทึกไว้",
  benchmarkNoPolicy: "ยังไม่มีนโยบาย threshold ที่เจ้าของอนุมัติ",
  benchmarkIncomplete: "รอบประเมินนี้ยังไม่สมบูรณ์และยังไม่คำนวณคะแนน เนื่องจากผลอัตโนมัติที่เลือกไม่อยู่ในสถานะให้ประเมินได้",
  benchmarkBlockers: "เหตุผลที่ยังประเมินไม่ได้",
  benchmarkThresholds: "ผลการตรวจ threshold",
  benchmarkThresholdPolicy: "ฉบับนโยบาย",
  benchmarkThresholdMetric: "เส้นทางเมตริก",
  benchmarkThresholdObserved: "ค่าที่พบ",
  benchmarkThresholdRequired: "ค่าที่กำหนด",
  benchmarkThresholdAvailability: "ความพร้อมของค่า",
  benchmarkThresholdResult: "ผลลัพธ์",
  benchmarkThresholdReason: "เหตุผล",
  benchmarkThresholdPass: "ผ่าน",
  benchmarkThresholdFail: "รอ",
  pilotRelease: "รุ่น Pilot",
  versionLabel: "เวอร์ชัน",
  currentRun: "งานประมวลผลปัจจุบัน",
  selectRun: "เลือกงาน",
  selectedRun: "เลือกแล้ว",
  runHistory: "ประวัติงานประมวลผล",
  runSelectionHelp: "เลือกงานที่เสร็จแล้วอย่างชัดเจน งานเดิมยังคงอยู่และระบบจะไม่เปลี่ยนงานปัจจุบันให้เอง",
  runNotReady: "เลือกได้เฉพาะงานที่เสร็จและมีผลลัพธ์แล้ว",
  coreReady: "ระบบหลักพร้อมใช้งาน",
  processingBlocked: "การประมวลผลจริงยังไม่พร้อม",
  readinessComponents: "องค์ประกอบความพร้อม"
} as const;

export const copy = {
  th,
  en
} as const;
