ALTER TABLE projects ADD COLUMN updated_at TEXT;
ALTER TABLE projects ADD COLUMN version INTEGER NOT NULL DEFAULT 1;

ALTER TABLE video_sources ADD COLUMN source_type TEXT NOT NULL DEFAULT 'mock';
ALTER TABLE video_sources ADD COLUMN original_filename TEXT;
ALTER TABLE video_sources ADD COLUMN managed_media_path TEXT;
ALTER TABLE video_sources ADD COLUMN byte_size INTEGER;
ALTER TABLE video_sources ADD COLUMN fingerprint_strategy TEXT NOT NULL DEFAULT 'sha256-existing-field';
ALTER TABLE video_sources ADD COLUMN container_format TEXT;
ALTER TABLE video_sources ADD COLUMN video_codec TEXT;
ALTER TABLE video_sources ADD COLUMN duration_ms INTEGER;
ALTER TABLE video_sources ADD COLUMN width INTEGER;
ALTER TABLE video_sources ADD COLUMN height INTEGER;
ALTER TABLE video_sources ADD COLUMN sample_aspect_ratio TEXT;
ALTER TABLE video_sources ADD COLUMN display_aspect_ratio TEXT;
ALTER TABLE video_sources ADD COLUMN nominal_frame_rate TEXT;
ALTER TABLE video_sources ADD COLUMN average_frame_rate TEXT;
ALTER TABLE video_sources ADD COLUMN stream_time_base TEXT;
ALTER TABLE video_sources ADD COLUMN start_pts INTEGER;
ALTER TABLE video_sources ADD COLUMN first_video_pts INTEGER;
ALTER TABLE video_sources ADD COLUMN frame_count INTEGER;
ALTER TABLE video_sources ADD COLUMN variable_frame_rate INTEGER NOT NULL DEFAULT 0;
ALTER TABLE video_sources ADD COLUMN rotation_degrees INTEGER;
ALTER TABLE video_sources ADD COLUMN metadata_creation_time TEXT;
ALTER TABLE video_sources ADD COLUMN inspection_warnings_json TEXT NOT NULL DEFAULT '[]';
ALTER TABLE video_sources ADD COLUMN inspection_tool TEXT;
ALTER TABLE video_sources ADD COLUMN inspection_tool_version TEXT;
ALTER TABLE video_sources ADD COLUMN user_start_local TEXT;
ALTER TABLE video_sources ADD COLUMN user_start_timezone TEXT;
ALTER TABLE video_sources ADD COLUMN user_start_instant TEXT;
ALTER TABLE video_sources ADD COLUMN source_offset_ms INTEGER NOT NULL DEFAULT 0;
ALTER TABLE video_sources ADD COLUMN analysis_window_start_ms INTEGER;
ALTER TABLE video_sources ADD COLUMN analysis_window_end_ms INTEGER;
ALTER TABLE video_sources ADD COLUMN end_boundary_policy TEXT NOT NULL DEFAULT '[start,end)';
